const data ={
    products:[
        {
            _id :'1',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'../images/p1.jpg', 
            price:500,
            brand:'Nike',
            rating:47,
            numReviews:10,
            countInStock:1,
            description:'high quality product',
        },

        {
            _id :'2',
            name:'Adidas Slim Shirt',
            category:'Shirts',
            image:'../images/p1.jpg', 
            price:200,
            brand:'Adidas',
            rating:15,
            numReviews:12,
            countInStock:2,
            description:'high quality product',
        },
        {
            _id :'3',
            name:'Mpuma Slim Shirt',
            category:'Shirts',
            image:'../images/p1.jpg', 
            price:520,
            brand:'Nike',
            rating:8,
            numReviews:18,
            countInStock:0,
            description:'high quality product',
        },
        {
            _id :'4',
            name:'Raph Slim Shirt',
            category:'Shirts',
            image:'../images/p1.jpg', 
            price:620,
            brand:'Nike',
            rating:9,
            numReviews:11,
            countInStock:0,
            description:'high quality product',
        },
        {
            _id :'5',
            name:'Fendi Slim Shirt',
            category:'Shirts',
            image:'../images/p1.jpg', 
            price:400,
            brand:'Nike',
            rating:7,
            numReviews:17,
            countInStock:5,
            description:'high quality product',
        },
        {
            _id :'6',
            name:'Rock Slim Shirt',
            category:'Shirts',
            image:'../images/p1.jpg', 
            price:720,
            brand:'Nike',
            rating:5,
            numReviews:18,
            countInStock:0,
            description:'high quality product',
        },

    ]
}
export default data;
